// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/token/v1/token.proto

package tokenv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Token represents a cryptocurrency token with its metadata
type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // UUID
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                            // Contract address (0x...)
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                  // Token name
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`                              // Token symbol (BTC, ETH, etc)
	Decimals      uint32                 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`                         // Number of decimal places
	TotalSupply   string                 `protobuf:"bytes,6,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"` // Total supply (string for big numbers)
	Chain         string                 `protobuf:"bytes,7,opt,name=chain,proto3" json:"chain,omitempty"`                                // Blockchain (ethereum, bsc, polygon, etc)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Deleted       bool                   `protobuf:"varint,11,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_proto_token_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Token) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Token) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Token) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Token) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *Token) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *Token) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Token) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Token) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Token) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Token) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// TokenMetric represents market metrics for a token at a specific time
type TokenMetric struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                         // Metric ID
	TokenId               string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                                                // Foreign key to Token
	TokenAddress          string                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`                                 // Denormalized address
	Chain                 string                 `protobuf:"bytes,4,opt,name=chain,proto3" json:"chain,omitempty"`                                                                   // Blockchain network
	Price                 float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`                                                                 // Current price in USD
	PriceChange_24H       float64                `protobuf:"fixed64,6,opt,name=price_change_24h,json=priceChange24h,proto3" json:"price_change_24h,omitempty"`                       // Price change % (24h)
	PriceChange_7D        float64                `protobuf:"fixed64,7,opt,name=price_change_7d,json=priceChange7d,proto3" json:"price_change_7d,omitempty"`                          // Price change % (7d)
	Volume_24H            float64                `protobuf:"fixed64,8,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`                                        // Trading volume (24h)
	MarketCap             float64                `protobuf:"fixed64,9,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`                                        // Market capitalization
	Holders               int64                  `protobuf:"varint,10,opt,name=holders,proto3" json:"holders,omitempty"`                                                             // Number of holders
	Transactions_24H      int64                  `protobuf:"varint,11,opt,name=transactions_24h,json=transactions24h,proto3" json:"transactions_24h,omitempty"`                      // Transaction count (24h)
	LiquidityUsd          float64                `protobuf:"fixed64,12,opt,name=liquidity_usd,json=liquidityUsd,proto3" json:"liquidity_usd,omitempty"`                              // Total liquidity in USD
	FullyDilutedValuation float64                `protobuf:"fixed64,13,opt,name=fully_diluted_valuation,json=fullyDilutedValuation,proto3" json:"fully_diluted_valuation,omitempty"` // FDV
	Timestamp             *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeletedAt             *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Deleted               bool                   `protobuf:"varint,16,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TokenMetric) Reset() {
	*x = TokenMetric{}
	mi := &file_proto_token_v1_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMetric) ProtoMessage() {}

func (x *TokenMetric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenMetric.ProtoReflect.Descriptor instead.
func (*TokenMetric) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{1}
}

func (x *TokenMetric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenMetric) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TokenMetric) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenMetric) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *TokenMetric) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TokenMetric) GetPriceChange_24H() float64 {
	if x != nil {
		return x.PriceChange_24H
	}
	return 0
}

func (x *TokenMetric) GetPriceChange_7D() float64 {
	if x != nil {
		return x.PriceChange_7D
	}
	return 0
}

func (x *TokenMetric) GetVolume_24H() float64 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *TokenMetric) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *TokenMetric) GetHolders() int64 {
	if x != nil {
		return x.Holders
	}
	return 0
}

func (x *TokenMetric) GetTransactions_24H() int64 {
	if x != nil {
		return x.Transactions_24H
	}
	return 0
}

func (x *TokenMetric) GetLiquidityUsd() float64 {
	if x != nil {
		return x.LiquidityUsd
	}
	return 0
}

func (x *TokenMetric) GetFullyDilutedValuation() float64 {
	if x != nil {
		return x.FullyDilutedValuation
	}
	return 0
}

func (x *TokenMetric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TokenMetric) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *TokenMetric) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// PricePoint represents a single price data point in history
type PricePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Open          float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	MarketCap     float64                `protobuf:"fixed64,7,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricePoint) Reset() {
	*x = PricePoint{}
	mi := &file_proto_token_v1_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricePoint) ProtoMessage() {}

func (x *PricePoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricePoint.ProtoReflect.Descriptor instead.
func (*PricePoint) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{2}
}

func (x *PricePoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PricePoint) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *PricePoint) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *PricePoint) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *PricePoint) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *PricePoint) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *PricePoint) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

// Holder represents a token holder with their balance
type Holder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`                          // Balance as string (big numbers)
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`                  // Percentage of total supply
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`                              // Optional label (CEX, DEX, etc)
	IsContract    bool                   `protobuf:"varint,5,opt,name=is_contract,json=isContract,proto3" json:"is_contract,omitempty"` // Whether address is a contract
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holder) Reset() {
	*x = Holder{}
	mi := &file_proto_token_v1_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holder) ProtoMessage() {}

func (x *Holder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holder.ProtoReflect.Descriptor instead.
func (*Holder) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{3}
}

func (x *Holder) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Holder) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Holder) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Holder) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Holder) GetIsContract() bool {
	if x != nil {
		return x.IsContract
	}
	return false
}

// Transaction represents a token transaction
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hash            string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From            string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To              string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value           string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // Transaction amount
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockNumber     uint64                 `protobuf:"varint,6,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TransactionType string                 `protobuf:"bytes,7,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // transfer, swap, mint, burn
	ValueUsd        float64                `protobuf:"fixed64,8,opt,name=value_usd,json=valueUsd,proto3" json:"value_usd,omitempty"`                    // USD value at time of tx
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_token_v1_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{4}
}

func (x *Transaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Transaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Transaction) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Transaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *Transaction) GetValueUsd() float64 {
	if x != nil {
		return x.ValueUsd
	}
	return 0
}

// TrendingToken represents a trending token with score
type TrendingToken struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Metrics        *TokenMetric           `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	TrendingScore  float64                `protobuf:"fixed64,3,opt,name=trending_score,json=trendingScore,proto3" json:"trending_score,omitempty"`  // Algorithm-based score
	TrendingReason string                 `protobuf:"bytes,4,opt,name=trending_reason,json=trendingReason,proto3" json:"trending_reason,omitempty"` // Why it's trending
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrendingToken) Reset() {
	*x = TrendingToken{}
	mi := &file_proto_token_v1_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingToken) ProtoMessage() {}

func (x *TrendingToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingToken.ProtoReflect.Descriptor instead.
func (*TrendingToken) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{5}
}

func (x *TrendingToken) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *TrendingToken) GetMetrics() *TokenMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TrendingToken) GetTrendingScore() float64 {
	if x != nil {
		return x.TrendingScore
	}
	return 0
}

func (x *TrendingToken) GetTrendingReason() string {
	if x != nil {
		return x.TrendingReason
	}
	return ""
}

// PriceAlert represents a user-configured price alert
type PriceAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Chain         string                 `protobuf:"bytes,4,opt,name=chain,proto3" json:"chain,omitempty"`
	TargetPrice   float64                `protobuf:"fixed64,5,opt,name=target_price,json=targetPrice,proto3" json:"target_price,omitempty"`
	Condition     string                 `protobuf:"bytes,6,opt,name=condition,proto3" json:"condition,omitempty"` // above, below, crosses
	Active        bool                   `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TriggeredAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceAlert) Reset() {
	*x = PriceAlert{}
	mi := &file_proto_token_v1_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceAlert) ProtoMessage() {}

func (x *PriceAlert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceAlert.ProtoReflect.Descriptor instead.
func (*PriceAlert) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{6}
}

func (x *PriceAlert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PriceAlert) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PriceAlert) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *PriceAlert) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *PriceAlert) GetTargetPrice() float64 {
	if x != nil {
		return x.TargetPrice
	}
	return 0
}

func (x *PriceAlert) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *PriceAlert) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *PriceAlert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PriceAlert) GetTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAt
	}
	return nil
}

// HealthCheckResponse is a simple message to indicate service health status.
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                              // "ok" or "error"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                            // Service version
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Name of the service
	Env           string                 `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`                                    // Environment (production, staging, etc)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_token_v1_token_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthCheckResponse) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// GetTokenRequest is the request message for retrieving a token by its unique identifier.
type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_proto_token_v1_token_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{8}
}

func (x *GetTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListTokensResponse is the response message containing a list of tokens.
type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*Token               `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_proto_token_v1_token_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{9}
}

func (x *ListTokensResponse) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListTokensResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTokensResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTokensResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTokensRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Chain          string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`                                         // Filter by chain (optional)
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                        // Pagination limit (default: 50)
	Offset         int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                                      // Pagination offset
	OrderBy        string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`                      // Order field (created_at, symbol, etc)
	OrderDirection string                 `protobuf:"bytes,5,opt,name=order_direction,json=orderDirection,proto3" json:"order_direction,omitempty"` // asc or desc
	Search         string                 `protobuf:"bytes,6,opt,name=search,proto3" json:"search,omitempty"`                                       // Search by name or symbol
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_proto_token_v1_token_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{10}
}

func (x *ListTokensRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ListTokensRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTokensRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTokensRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListTokensRequest) GetOrderDirection() string {
	if x != nil {
		return x.OrderDirection
	}
	return ""
}

func (x *ListTokensRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

var File_proto_token_v1_token_proto protoreflect.FileDescriptor

const file_proto_token_v1_token_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/token/v1/token.proto\x12\btoken.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfd\x02\n" +
	"\x05Token\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\rR\bdecimals\x12!\n" +
	"\ftotal_supply\x18\x06 \x01(\tR\vtotalSupply\x12\x14\n" +
	"\x05chain\x18\a \x01(\tR\x05chain\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x18\n" +
	"\adeleted\x18\v \x01(\bR\adeleted\"\xca\x04\n" +
	"\vTokenMetric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05chain\x18\x04 \x01(\tR\x05chain\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12(\n" +
	"\x10price_change_24h\x18\x06 \x01(\x01R\x0epriceChange24h\x12&\n" +
	"\x0fprice_change_7d\x18\a \x01(\x01R\rpriceChange7d\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\b \x01(\x01R\tvolume24h\x12\x1d\n" +
	"\n" +
	"market_cap\x18\t \x01(\x01R\tmarketCap\x12\x18\n" +
	"\aholders\x18\n" +
	" \x01(\x03R\aholders\x12)\n" +
	"\x10transactions_24h\x18\v \x01(\x03R\x0ftransactions24h\x12#\n" +
	"\rliquidity_usd\x18\f \x01(\x01R\fliquidityUsd\x126\n" +
	"\x17fully_diluted_valuation\x18\r \x01(\x01R\x15fullyDilutedValuation\x128\n" +
	"\ttimestamp\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\n" +
	"deleted_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x18\n" +
	"\adeleted\x18\x10 \x01(\bR\adeleted\"\xcd\x01\n" +
	"\n" +
	"PricePoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\x12\x1d\n" +
	"\n" +
	"market_cap\x18\a \x01(\x01R\tmarketCap\"\x93\x01\n" +
	"\x06Holder\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x1f\n" +
	"\vis_contract\x18\x05 \x01(\bR\n" +
	"isContract\"\x80\x02\n" +
	"\vTransaction\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fblock_number\x18\x06 \x01(\x04R\vblockNumber\x12)\n" +
	"\x10transaction_type\x18\a \x01(\tR\x0ftransactionType\x12\x1b\n" +
	"\tvalue_usd\x18\b \x01(\x01R\bvalueUsd\"\xb7\x01\n" +
	"\rTrendingToken\x12%\n" +
	"\x05token\x18\x01 \x01(\v2\x0f.token.v1.TokenR\x05token\x12/\n" +
	"\ametrics\x18\x02 \x01(\v2\x15.token.v1.TokenMetricR\ametrics\x12%\n" +
	"\x0etrending_score\x18\x03 \x01(\x01R\rtrendingScore\x12'\n" +
	"\x0ftrending_reason\x18\x04 \x01(\tR\x0etrendingReason\"\xc3\x02\n" +
	"\n" +
	"PriceAlert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05chain\x18\x04 \x01(\tR\x05chain\x12!\n" +
	"\ftarget_price\x18\x05 \x01(\x01R\vtargetPrice\x12\x1c\n" +
	"\tcondition\x18\x06 \x01(\tR\tcondition\x12\x16\n" +
	"\x06active\x18\a \x01(\bR\x06active\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\ftriggered_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vtriggeredAt\"|\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\"!\n" +
	"\x0fGetTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x81\x01\n" +
	"\x12ListTokensResponse\x12'\n" +
	"\x06tokens\x18\x01 \x03(\v2\x0f.token.v1.TokenR\x06tokens\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xb3\x01\n" +
	"\x11ListTokensRequest\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\x12'\n" +
	"\x0forder_direction\x18\x05 \x01(\tR\x0eorderDirection\x12\x16\n" +
	"\x06search\x18\x06 \x01(\tR\x06search2\x9a\x02\n" +
	"\fTokenService\x12X\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1d.token.v1.HealthCheckResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/health\x12S\n" +
	"\fGetTokenById\x12\x19.token.v1.GetTokenRequest\x1a\x0f.token.v1.Token\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/tokens/{id}\x12[\n" +
	"\n" +
	"ListTokens\x12\x1b.token.v1.ListTokensRequest\x1a\x1c.token.v1.ListTokensResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/tokensB\x1eZ\x1cinternal/pb/token/v1;tokenv1b\x06proto3"

var (
	file_proto_token_v1_token_proto_rawDescOnce sync.Once
	file_proto_token_v1_token_proto_rawDescData []byte
)

func file_proto_token_v1_token_proto_rawDescGZIP() []byte {
	file_proto_token_v1_token_proto_rawDescOnce.Do(func() {
		file_proto_token_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_v1_token_proto_rawDesc), len(file_proto_token_v1_token_proto_rawDesc)))
	})
	return file_proto_token_v1_token_proto_rawDescData
}

var file_proto_token_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_token_v1_token_proto_goTypes = []any{
	(*Token)(nil),                 // 0: token.v1.Token
	(*TokenMetric)(nil),           // 1: token.v1.TokenMetric
	(*PricePoint)(nil),            // 2: token.v1.PricePoint
	(*Holder)(nil),                // 3: token.v1.Holder
	(*Transaction)(nil),           // 4: token.v1.Transaction
	(*TrendingToken)(nil),         // 5: token.v1.TrendingToken
	(*PriceAlert)(nil),            // 6: token.v1.PriceAlert
	(*HealthCheckResponse)(nil),   // 7: token.v1.HealthCheckResponse
	(*GetTokenRequest)(nil),       // 8: token.v1.GetTokenRequest
	(*ListTokensResponse)(nil),    // 9: token.v1.ListTokensResponse
	(*ListTokensRequest)(nil),     // 10: token.v1.ListTokensRequest
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_proto_token_v1_token_proto_depIdxs = []int32{
	11, // 0: token.v1.Token.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: token.v1.Token.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: token.v1.Token.deleted_at:type_name -> google.protobuf.Timestamp
	11, // 3: token.v1.TokenMetric.timestamp:type_name -> google.protobuf.Timestamp
	11, // 4: token.v1.TokenMetric.deleted_at:type_name -> google.protobuf.Timestamp
	11, // 5: token.v1.PricePoint.timestamp:type_name -> google.protobuf.Timestamp
	11, // 6: token.v1.Transaction.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 7: token.v1.TrendingToken.token:type_name -> token.v1.Token
	1,  // 8: token.v1.TrendingToken.metrics:type_name -> token.v1.TokenMetric
	11, // 9: token.v1.PriceAlert.created_at:type_name -> google.protobuf.Timestamp
	11, // 10: token.v1.PriceAlert.triggered_at:type_name -> google.protobuf.Timestamp
	0,  // 11: token.v1.ListTokensResponse.tokens:type_name -> token.v1.Token
	12, // 12: token.v1.TokenService.HealthCheck:input_type -> google.protobuf.Empty
	8,  // 13: token.v1.TokenService.GetTokenById:input_type -> token.v1.GetTokenRequest
	10, // 14: token.v1.TokenService.ListTokens:input_type -> token.v1.ListTokensRequest
	7,  // 15: token.v1.TokenService.HealthCheck:output_type -> token.v1.HealthCheckResponse
	0,  // 16: token.v1.TokenService.GetTokenById:output_type -> token.v1.Token
	9,  // 17: token.v1.TokenService.ListTokens:output_type -> token.v1.ListTokensResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_token_v1_token_proto_init() }
func file_proto_token_v1_token_proto_init() {
	if File_proto_token_v1_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_v1_token_proto_rawDesc), len(file_proto_token_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_token_v1_token_proto_goTypes,
		DependencyIndexes: file_proto_token_v1_token_proto_depIdxs,
		MessageInfos:      file_proto_token_v1_token_proto_msgTypes,
	}.Build()
	File_proto_token_v1_token_proto = out.File
	file_proto_token_v1_token_proto_goTypes = nil
	file_proto_token_v1_token_proto_depIdxs = nil
}
