// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/token/v1/token.proto

package tokenv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Token represents a cryptocurrency token with its metadata
type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                        // UUID
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                              // Contract address (0x...)
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                    // Token name
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`                                // Token symbol (BTC, ETH, etc)
	Decimals      uint32                 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`                           // Number of decimal places
	TotalSupply   float64                `protobuf:"fixed64,6,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"` // Total supply
	Chain         string                 `protobuf:"bytes,7,opt,name=chain,proto3" json:"chain,omitempty"`                                  // Blockchain (ethereum, bsc, polygon, etc)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Deleted       bool                   `protobuf:"varint,11,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_proto_token_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Token) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Token) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Token) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Token) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *Token) GetTotalSupply() float64 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

func (x *Token) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Token) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Token) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Token) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Token) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// HealthCheckResponse is a simple message to indicate service health status.
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                              // "ok" or "error"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                            // Service version
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Name of the service
	Env           string                 `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`                                    // Environment (production, staging, etc)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_token_v1_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthCheckResponse) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// GetTokenRequest is the request message for retrieving a token by its unique identifier.
type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_proto_token_v1_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{2}
}

func (x *GetTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListTokensResponse is the response message containing a list of tokens.
type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*Token               `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_proto_token_v1_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{3}
}

func (x *ListTokensResponse) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListTokensResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTokensResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTokensResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTokensRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Chain          string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`                                         // Filter by chain (optional)
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                        // Pagination limit (default: 50)
	Offset         int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                                      // Pagination offset
	OrderBy        string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`                      // Order field (created_at, symbol, etc)
	OrderDirection string                 `protobuf:"bytes,5,opt,name=order_direction,json=orderDirection,proto3" json:"order_direction,omitempty"` // asc or desc
	Search         string                 `protobuf:"bytes,6,opt,name=search,proto3" json:"search,omitempty"`                                       // Search by name or symbol
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_proto_token_v1_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{4}
}

func (x *ListTokensRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ListTokensRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTokensRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTokensRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListTokensRequest) GetOrderDirection() string {
	if x != nil {
		return x.OrderDirection
	}
	return ""
}

func (x *ListTokensRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

var File_proto_token_v1_token_proto protoreflect.FileDescriptor

const file_proto_token_v1_token_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/token/v1/token.proto\x12\btoken.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfd\x02\n" +
	"\x05Token\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\rR\bdecimals\x12!\n" +
	"\ftotal_supply\x18\x06 \x01(\x01R\vtotalSupply\x12\x14\n" +
	"\x05chain\x18\a \x01(\tR\x05chain\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x18\n" +
	"\adeleted\x18\v \x01(\bR\adeleted\"|\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\"!\n" +
	"\x0fGetTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x81\x01\n" +
	"\x12ListTokensResponse\x12'\n" +
	"\x06tokens\x18\x01 \x03(\v2\x0f.token.v1.TokenR\x06tokens\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xb3\x01\n" +
	"\x11ListTokensRequest\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\x12'\n" +
	"\x0forder_direction\x18\x05 \x01(\tR\x0eorderDirection\x12\x16\n" +
	"\x06search\x18\x06 \x01(\tR\x06search2\x9a\x02\n" +
	"\fTokenService\x12X\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1d.token.v1.HealthCheckResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/health\x12S\n" +
	"\fGetTokenById\x12\x19.token.v1.GetTokenRequest\x1a\x0f.token.v1.Token\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/tokens/{id}\x12[\n" +
	"\n" +
	"ListTokens\x12\x1b.token.v1.ListTokensRequest\x1a\x1c.token.v1.ListTokensResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/tokensB\x1eZ\x1cinternal/pb/token/v1;tokenv1b\x06proto3"

var (
	file_proto_token_v1_token_proto_rawDescOnce sync.Once
	file_proto_token_v1_token_proto_rawDescData []byte
)

func file_proto_token_v1_token_proto_rawDescGZIP() []byte {
	file_proto_token_v1_token_proto_rawDescOnce.Do(func() {
		file_proto_token_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_v1_token_proto_rawDesc), len(file_proto_token_v1_token_proto_rawDesc)))
	})
	return file_proto_token_v1_token_proto_rawDescData
}

var file_proto_token_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_token_v1_token_proto_goTypes = []any{
	(*Token)(nil),                 // 0: token.v1.Token
	(*HealthCheckResponse)(nil),   // 1: token.v1.HealthCheckResponse
	(*GetTokenRequest)(nil),       // 2: token.v1.GetTokenRequest
	(*ListTokensResponse)(nil),    // 3: token.v1.ListTokensResponse
	(*ListTokensRequest)(nil),     // 4: token.v1.ListTokensRequest
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_proto_token_v1_token_proto_depIdxs = []int32{
	5, // 0: token.v1.Token.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: token.v1.Token.updated_at:type_name -> google.protobuf.Timestamp
	5, // 2: token.v1.Token.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 3: token.v1.ListTokensResponse.tokens:type_name -> token.v1.Token
	6, // 4: token.v1.TokenService.HealthCheck:input_type -> google.protobuf.Empty
	2, // 5: token.v1.TokenService.GetTokenById:input_type -> token.v1.GetTokenRequest
	4, // 6: token.v1.TokenService.ListTokens:input_type -> token.v1.ListTokensRequest
	1, // 7: token.v1.TokenService.HealthCheck:output_type -> token.v1.HealthCheckResponse
	0, // 8: token.v1.TokenService.GetTokenById:output_type -> token.v1.Token
	3, // 9: token.v1.TokenService.ListTokens:output_type -> token.v1.ListTokensResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_token_v1_token_proto_init() }
func file_proto_token_v1_token_proto_init() {
	if File_proto_token_v1_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_v1_token_proto_rawDesc), len(file_proto_token_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_token_v1_token_proto_goTypes,
		DependencyIndexes: file_proto_token_v1_token_proto_depIdxs,
		MessageInfos:      file_proto_token_v1_token_proto_msgTypes,
	}.Build()
	File_proto_token_v1_token_proto = out.File
	file_proto_token_v1_token_proto_goTypes = nil
	file_proto_token_v1_token_proto_depIdxs = nil
}
