// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/token/v1/token.proto

package tokenv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Token represents a cryptocurrency token with its associated metadata and metrics.
type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals      uint32                 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	TotalSupply   float64                `protobuf:"fixed64,6,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	Chain         string                 `protobuf:"bytes,7,opt,name=chain,proto3" json:"chain,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Deleted       bool                   `protobuf:"varint,11,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_proto_token_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Token) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Token) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Token) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Token) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *Token) GetTotalSupply() float64 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

func (x *Token) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Token) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Token) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Token) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Token) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// TokenMetric represents the latest market metrics for a specific token.
type TokenMetric struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TokenId          string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenAddress     string                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Price            float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	PriceChange_24H  float64                `protobuf:"fixed64,5,opt,name=price_change_24h,json=priceChange24h,proto3" json:"price_change_24h,omitempty"`
	Volume_24H       float64                `protobuf:"fixed64,6,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`
	MarketCap        float64                `protobuf:"fixed64,7,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	Holders          int64                  `protobuf:"varint,8,opt,name=holders,proto3" json:"holders,omitempty"`
	Transactions_24H int64                  `protobuf:"varint,9,opt,name=transactions_24h,json=transactions24h,proto3" json:"transactions_24h,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Deleted          bool                   `protobuf:"varint,12,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenMetric) Reset() {
	*x = TokenMetric{}
	mi := &file_proto_token_v1_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMetric) ProtoMessage() {}

func (x *TokenMetric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenMetric.ProtoReflect.Descriptor instead.
func (*TokenMetric) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{1}
}

func (x *TokenMetric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenMetric) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TokenMetric) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenMetric) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TokenMetric) GetPriceChange_24H() float64 {
	if x != nil {
		return x.PriceChange_24H
	}
	return 0
}

func (x *TokenMetric) GetVolume_24H() float64 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *TokenMetric) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *TokenMetric) GetHolders() int64 {
	if x != nil {
		return x.Holders
	}
	return 0
}

func (x *TokenMetric) GetTransactions_24H() int64 {
	if x != nil {
		return x.Transactions_24H
	}
	return 0
}

func (x *TokenMetric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TokenMetric) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *TokenMetric) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// Blank message for requests that do not require any parameters.
type Blank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blank) Reset() {
	*x = Blank{}
	mi := &file_proto_token_v1_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blank) ProtoMessage() {}

func (x *Blank) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blank.ProtoReflect.Descriptor instead.
func (*Blank) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{2}
}

// GetTokenRequest is the request message for retrieving a token by its unique identifier.
type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_proto_token_v1_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{3}
}

func (x *GetTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListTokensResponse is the response message containing a list of tokens.
type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*Token               `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_proto_token_v1_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_v1_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_v1_token_proto_rawDescGZIP(), []int{4}
}

func (x *ListTokensResponse) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

var File_proto_token_v1_token_proto protoreflect.FileDescriptor

const file_proto_token_v1_token_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/token/v1/token.proto\x12\btoken.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x02\n" +
	"\x05Token\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\rR\bdecimals\x12!\n" +
	"\ftotal_supply\x18\x06 \x01(\x01R\vtotalSupply\x12\x14\n" +
	"\x05chain\x18\a \x01(\tR\x05chain\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x18\n" +
	"\adeleted\x18\v \x01(\bR\adeleted\"\xaf\x03\n" +
	"\vTokenMetric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12(\n" +
	"\x10price_change_24h\x18\x05 \x01(\x01R\x0epriceChange24h\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\x06 \x01(\x01R\tvolume24h\x12\x1d\n" +
	"\n" +
	"market_cap\x18\a \x01(\x01R\tmarketCap\x12\x18\n" +
	"\aholders\x18\b \x01(\x03R\aholders\x12)\n" +
	"\x10transactions_24h\x18\t \x01(\x03R\x0ftransactions24h\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\n" +
	"deleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x18\n" +
	"\adeleted\x18\f \x01(\bR\adeleted\"\a\n" +
	"\x05Blank\"!\n" +
	"\x0fGetTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x12ListTokensResponse\x12'\n" +
	"\x06tokens\x18\x01 \x03(\v2\x0f.token.v1.TokenR\x06tokens2\xb4\x01\n" +
	"\fTokenService\x12S\n" +
	"\fGetTokenById\x12\x19.token.v1.GetTokenRequest\x1a\x0f.token.v1.Token\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/tokens/{id}\x12O\n" +
	"\n" +
	"ListTokens\x12\x0f.token.v1.Blank\x1a\x1c.token.v1.ListTokensResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/tokensB\x1eZ\x1cinternal/pb/token/v1;tokenv1b\x06proto3"

var (
	file_proto_token_v1_token_proto_rawDescOnce sync.Once
	file_proto_token_v1_token_proto_rawDescData []byte
)

func file_proto_token_v1_token_proto_rawDescGZIP() []byte {
	file_proto_token_v1_token_proto_rawDescOnce.Do(func() {
		file_proto_token_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_v1_token_proto_rawDesc), len(file_proto_token_v1_token_proto_rawDesc)))
	})
	return file_proto_token_v1_token_proto_rawDescData
}

var file_proto_token_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_token_v1_token_proto_goTypes = []any{
	(*Token)(nil),                 // 0: token.v1.Token
	(*TokenMetric)(nil),           // 1: token.v1.TokenMetric
	(*Blank)(nil),                 // 2: token.v1.Blank
	(*GetTokenRequest)(nil),       // 3: token.v1.GetTokenRequest
	(*ListTokensResponse)(nil),    // 4: token.v1.ListTokensResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_token_v1_token_proto_depIdxs = []int32{
	5, // 0: token.v1.Token.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: token.v1.Token.updated_at:type_name -> google.protobuf.Timestamp
	5, // 2: token.v1.Token.deleted_at:type_name -> google.protobuf.Timestamp
	5, // 3: token.v1.TokenMetric.timestamp:type_name -> google.protobuf.Timestamp
	5, // 4: token.v1.TokenMetric.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 5: token.v1.ListTokensResponse.tokens:type_name -> token.v1.Token
	3, // 6: token.v1.TokenService.GetTokenById:input_type -> token.v1.GetTokenRequest
	2, // 7: token.v1.TokenService.ListTokens:input_type -> token.v1.Blank
	0, // 8: token.v1.TokenService.GetTokenById:output_type -> token.v1.Token
	4, // 9: token.v1.TokenService.ListTokens:output_type -> token.v1.ListTokensResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_token_v1_token_proto_init() }
func file_proto_token_v1_token_proto_init() {
	if File_proto_token_v1_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_v1_token_proto_rawDesc), len(file_proto_token_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_token_v1_token_proto_goTypes,
		DependencyIndexes: file_proto_token_v1_token_proto_depIdxs,
		MessageInfos:      file_proto_token_v1_token_proto_msgTypes,
	}.Build()
	File_proto_token_v1_token_proto = out.File
	file_proto_token_v1_token_proto_goTypes = nil
	file_proto_token_v1_token_proto_depIdxs = nil
}
